### ISSUE TITLE
Caching of data on local storage to reduce API calls

### ISSUE THREAD

**Issue by bhavaanikakarla** [covidFYI/frontend#7]
Whenever an API request is hit, fetch the data and  store on local storage (i.e., cache)

If current time < last_data_fetch_from_GSheets + 12 hours, fetch data from cache and avoid API calls.
else if current time >= last_data_fetch_from_GSheets + 12 hours, call API

* This is applicable for all APIs

**Comment by tejasa97** [comment]
@yogesh-hackx you might wanna get on top of this ASAP

**Comment by yogesh-hackx** [comment]
DONE
